### ISSUE TITLE
Crash in OutgoingMutationQueue

### ISSUE THREAD

**Issue by kubatatami** [aws-amplify/amplify-swift#3325]
### Describe the bug

OutgoingMutationQueue Crashes.

Sample error reported:

```
Exception Type: EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: SEGV_ACCERR at 0x4075e00000000018
Crashed Thread: 15

Application Specific Information:
Signal 11, Code 2 >
Attempted to dereference garbage pointer at 0x4075e00000000018.
```

Sample Stacktraces:

```
Thread 15 Crashed:
0   Foundation                      0x32b5d7a2c         __NSOQSchedule
1   Foundation                      0x32b603f44         -[NSOperationQueue setSuspended:]
2   Evie Beta                       0x202906c78         OutgoingMutationQueue.doStart (OutgoingMutationQueue.swift:142)
3   Evie Beta                       0x202909c70         OutgoingMutationQueue.queryMutationEventsFromStorage (OutgoingMutationQueue.swift:342)
4   Evie Beta                       0x2028cf964         SQLiteStorageEngineAdapter.query<T> (StorageEngineAdapter+SQLite.swift:335)
5   Evie Beta                       0x2028d03b8         SQLiteStorageEngineAdapter.query<T> (StorageEngineAdapter+SQLite.swift:304)
6   Evie Beta                       0x2028d2018         SQLiteStorageEngineAdapter
7   Evie Beta                       0x202906f4c         OutgoingMutationQueue.queryMutationEventsFromStorage (OutgoingMutationQueue.swift:331)
8   Evie Beta                       0x202906804         OutgoingMutationQueue.doStart (OutgoingMutationQueue.swift:141)
9   Evie Beta                       0x202906138         OutgoingMutationQueue.respond (OutgoingMutationQueue.swift:109)
10  Evie Beta                       0x20290c86c         [inlined] OutgoingMutationQueue.init (OutgoingMutationQueue.swift:78)
11  Evie Beta                       0x20290c86c         OutgoingMutationQueue.init
12  Evie Beta                       0x20288c6c0         thunk for closure
13  libdispatch.dylib               0x33d44c6a4         _dispatch_call_block_and_release
14  libdispatch.dylib               0x33d44e2fc         _dispatch_client_callout
15  libdispatch.dylib               0x33d455890         _dispatch_lane_serial_drain
16  libdispatch.dylib               0x33d4563c0         _dispatch_lane_invoke
17  libdispatch.dylib               0x33d461000         _dispatch_root_queue_drain_deferred_wlh
18  libdispatch.dylib               0x33d460874         _dispatch_workloop_worker_thread
19  libsystem_pthread.dylib         0x3ff9cf960         _pthread_wqthread
```

### Steps To Reproduce

```swift
No steps to reproduce. Crash happens only sometimes.
```

### Expected behavior

No crash

### Amplify Framework Version

2.19.0

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5.9

### CLI version

12.2.3

### Xcode version

15.0

### Relevant log output

```shell
N/A
```

### Is this a regression?

No

### Platforms

iOS

### OS Version

all

### Device

all

**Comment by kubatatami** [comment]
@phantumcode Sorry, I can't share the schema of a single table because I don't know which of the multiple tables is causing the problem. I'm not the owner of the project. This is proprietary software, so I cannot share the entire database schema.

**Comment by thisisabhash** [comment]
Hello, Could you paste the verbose logs with sensitive information removed and reproduction steps so that we can try reproducing the issue. An approximate schema schema (for e.g. what model relations are present) and code snippets showing Amplify API calls would be helpful too.

On a side note, can you try upgrading to CLI 12.7.1 and Amplify Swift 2.21.4 to see if you're still facing the issues?

**Comment by kubatatami** [comment]
Hey @thisisabhash We don't have reproduction steps. It crashes randomly for our users and we were not able to reproduce it locally. We just have ~20 tables with timestamp as a key and a few primitive types(int, double etc) columns in each table. 
We use Amplify API in multiple places but mostly we do a simple `query` with `where` based on timestamp and simple `save`. We save a lot of rows but each row is small. 
We will update Amplify Swift and I will let you know if it helps.

**Comment by fzy-spyro** [comment]
we are having this crash in sdk v2.22.0 as well

**Comment by kubatatami** [comment]
@thisisabhash This is our “obfuscated” schema: [schema.txt](https://github.com/aws-amplify/amplify-swift/files/13635159/schema.txt)

**Comment by madej10** [comment]
@thisisabhash @atierian could you please let us know if there are any updates to this? We keep experiencing the issue.

**Comment by kubatatami** [comment]
Hey @lawmicha. No, it's not the same issue.

**Comment by lawmicha** [comment]
@kubatatami can you include the full crash report?

**Comment by kubatatami** [comment]
@lawmicha 

[fd10082803aa416b8d756321524bcb9e-symbolicated.txt](https://github.com/aws-amplify/amplify-swift/files/13717352/fd10082803aa416b8d756321524bcb9e-symbolicated.txt)

**Comment by lawmicha** [comment]
Hey @kubatatami I'm attempting to fix the crash in https://github.com/aws-amplify/amplify-swift/pull/3429 Could you try out this branch and let us know if you see any improvements? `lawmicha.fix-outgoing-queue`

**Comment by lawmicha** [comment]
The fix was released in https://github.com/aws-amplify/amplify-swift/releases/tag/2.25.2

**Comment by fzy-spyro** [comment]
@lawmicha We are still seeing the crash after update to amplify v.2.25.3. 
Created new issue: https://github.com/aws-amplify/amplify-swift/issues/3467
